server:
  tomcat:
    max-connections: 2000
    accept-count: 800
  port: 8099
  servlet:
    # 应用的访问路径
    context-path: /luckyLottery

spring:
  application:
    name: luckyLottery
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.186.204.64/infosmart_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: liyh63
    password: Apple520!
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.liyh.bean
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志

#eureka配置
eureka:
  client:
    #表示是否将自己注册进eureka  默认为true
    register-with-eureka: true
    #是否从EurekaServer中抓取已有的注册信息，默认为true，单点无所谓，集群必须设置true才能和ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #单机配置
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
